<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPxL3Dxd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPxL3Dxd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPxL3Dxd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPxL3Dxd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPxL3Dxd\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PxL3Dxd',
    'container.build_id' => '49e13ce2',
    'container.build_time' => 1645123544,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPxL3Dxd');
