<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYDN7AY7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYDN7AY7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYDN7AY7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYDN7AY7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYDN7AY7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YDN7AY7',
    'container.build_id' => '7dcdfdab',
    'container.build_time' => 1645440719,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYDN7AY7');
