<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9xezkzn\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9xezkzn/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9xezkzn.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9xezkzn\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container9xezkzn\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '9xezkzn',
    'container.build_id' => '5d7c6ed1',
    'container.build_time' => 1645989071,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9xezkzn');
